python_library(
    name='pex',
    srcs=['main.py'],
    resources=['//self-contained/resources:markov-model'],
    deps=['//self-contained/third-party:markovify', '//self-contained/third-party:piazza-api']
)